<?php

namespace DinoBundle\Repository;

/**
 * DinoDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DinoDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDinoData($dino, $rootPath)
    {
        $engLength = (string)$this->getEngLength($dino->getLength());
        $dino->setLengthEng($engLength);
//        $firstPhoto = $dino->getFirstPhoto();
//        $secondPhoto = $dino->getSecondPhoto();
//        $firstPhotoFileName = md5(uniqid()) . '.' . $firstPhoto->guessExtension();
//        $secondPhotoFileName = md5(uniqid()) . '.' . $secondPhoto->guessExtension();
//        
//        $firstPhoto->move(
//            $rootPath . '/photo/',
//            $firstPhotoFileName
//        );
//        
//        $secondPhoto->move(
//            $rootPath . '/photo/',
//            $secondPhotoFileName
//        );
//        
        $dino->setFirstPhoto($this->savePhoto($dino->getFirstPhoto(), $rootPath));
        $dino->setSecondPhoto($this->savePhoto($dino->getSecondPhoto(), $rootPath));
        
        return $dino;
    }
    
    public function getEngLength($length)
    {
        return $length * 3.28084;
    }
    
    public function savePhoto($photo, $rootPath)
    {   
        $photoFileName = md5(uniqid()) . '.' . $photo->guessExtension();

        $photo->move(
            $rootPath . '/photo/',
            $photoFileName
        );
//        dump($photoFileName);die;
        return $photoFileName;
    }
}
