<?php

namespace DinoBundle\Repository;

/**
 * DiscovererRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscovererRepository extends \Doctrine\ORM\EntityRepository
{
}
