<?php

namespace DinoBundle\Repository;

/**
 * InfraOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfraOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
