<?php

namespace DinoBundle\Repository;

/**
 * MainOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
