<?php

namespace DinoBundle\Repository;

/**
 * SubOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
