<?php

namespace DinoBundle\Repository;

/**
 * SubPeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubPeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
